[project]
name = "link-shorter"
version = "0.1.0"
description = "Сервис для сокращения ссылок"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "celery-types>=0.26.0",
    "celery[redis]>=5.4.0",
    "fastapi>=0.141.1",
    "pydantic-settings>=2.15.0",
    "redis>=5.0.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = ["F401", "B008"]

[dependency-groups]
dev = [
    "pylint>=4.0.7",
    "radon>=6.0.1",
    "ruff>=0.16.4",
    "pyright>=1.1.411",
]
