"""Rename prefix token field

Revision ID: 6ad4e7d1e1e4
Revises: b7da4bf12c58
Create Date: 2026-08-23 13:08:17.326656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad4e7d1e1e4'
down_revision: Union[str, Sequence[str], None] = 'b7da4bf12c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_links', sa.Column('token', sa.String(length=8), nullable=False))
    op.drop_constraint(op.f('short_links_prefix_key'), 'short_links', type_='unique')
    op.create_unique_constraint(None, 'short_links', ['token'])
    op.drop_column('short_links', 'prefix')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_links', sa.Column('prefix', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'short_links', type_='unique')
    op.create_unique_constraint(op.f('short_links_prefix_key'), 'short_links', ['prefix'], postgresql_nulls_not_distinct=False)
    op.drop_column('short_links', 'token')
    # ### end Alembic commands ###
